language: java
sudo: required
# trusty is required for oraclejdk9
dist: trusty

jdk:
  - oraclejdk8
  # JDK 9 disabled because of an incompatibility with JAI Image I/O that causes
  # the test log to exceed 4MB and Travis to kill the process; see
  # https://github.com/medusa-project/cantaloupe/issues/176
  - openjdk10

before_install:
  # install optional dependencies
  - sudo mkdir -p /usr/local/bin /usr/local/lib
  - sudo cp dist/deps/Linux-x86-64/bin/* /usr/local/bin
  - sudo cp dist/deps/Linux-x86-64/lib/* /usr/local/lib
  - export LIBRARY_PATH="/usr/local/lib:$LIBRARY_PATH"
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  # copy properties file
  - cp test.properties.sample test.properties
  # trusty used avconv, not ffmpeg, and tools like ffprobe are missing. So we need to add this repo
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  # no openjpeg2000 tools like opj_decompress for trusty as well, so adding this repo
  - sudo apt-get install apt-transport-https
  #- wget -O - https://notesalexp.org/debian/alexp_key.asc | sudo apt-key add -
  #- sudo apt-add-repository 'deb https://notesalexp.org/debian/trusty trusty main'
  # update and install all packages
  - sudo apt-get -qq update
  - sudo apt-get install -y libav-tools graphicsmagick imagemagick ffmpeg libopenjp2-tools

script:
  - mvn clean verify -Pfreedeps

services:
  - redis-server

#after_success:
#  - mvn clean cobertura:cobertura coveralls:report
