#
# N.B.: docker-compose must be invoked from the project root directory:
#
# docker compose -f path/to/compose.yaml up --exit-code-from cantaloupe
#
services:
  cantaloupe:
    build:
      context: ../../
      dockerfile: docker/Windows-JDK17/Dockerfile
  minio:
    build:
      context: ../../
      dockerfile: docker/Windows-JDK17/Dockerfile-minio
    environment:
      MINIO_ACCESS_KEY: MinioUser
      MINIO_SECRET_KEY: OpenSesame
    hostname: minio
