#
# N.B.: docker-compose must be invoked from the project root directory:
#
# docker-compose -f path/to/docker-compose.yml up --exit-code-from cantaloupe
#
version: '3'
services:
  cantaloupe:
    build:
      context: ../../
      dockerfile: $PWD/docker/Linux-JDK15/Dockerfile
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: MinioUser
      MINIO_SECRET_KEY: OpenSesame
    hostname: minio
    command: server /data
  redis:
    image: redis:alpine
    hostname: redis