# Site settings
title: Cantaloupe
email: alexd@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  High-performance dynamic image server in Java
baseurl: "/cantaloupe" # the subpath of your site, e.g. /blog
host: 0.0.0.0
url: "https://medusa-project.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: rouge
